// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

/*
Package dappserverpb is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	DAppServerConfig
*/
package dappserverpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Dappserver *DAppServerConfig `protobuf:"bytes,1,opt,name=dappserver" json:"dappserver"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{0} }

func (m *Config) GetDappserver() *DAppServerConfig {
	if m != nil {
		return m.Dappserver
	}
	return nil
}

type DAppServerConfig struct {
	// Enable
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable"`
	// Host
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host"`
	// Port
	Port uint64 `protobuf:"varint,3,opt,name=port,proto3" json:"port"`
	// Data dir
	DataDir string `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir"`
	// Max upload size
	MaxUploadSize uint64 `protobuf:"varint,5,opt,name=max_upload_size,json=maxUploadSize,proto3" json:"max_upload_size"`
	// ReadTimeout in millisecond
	ReadTimeoutMs uint64 `protobuf:"varint,6,opt,name=read_timeout_ms,json=readTimeoutMs,proto3" json:"read_timeout_ms"`
	// WriteTimeout in millisecond
	WriteTimeoutMs uint64 `protobuf:"varint,7,opt,name=write_timeout_ms,json=writeTimeoutMs,proto3" json:"write_timeout_ms"`
	// Log level
	LogLevel string `protobuf:"bytes,8,opt,name=log_level,json=logLevel,proto3" json:"log_level"`
	// Log file name
	LogFile string `protobuf:"bytes,9,opt,name=log_file,json=logFile,proto3" json:"log_file"`
	// Log file age, unit is s.
	LogAge uint32 `protobuf:"varint,10,opt,name=log_age,json=logAge,proto3" json:"log_age"`
}

func (m *DAppServerConfig) Reset()                    { *m = DAppServerConfig{} }
func (m *DAppServerConfig) String() string            { return proto.CompactTextString(m) }
func (*DAppServerConfig) ProtoMessage()               {}
func (*DAppServerConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{1} }

func (m *DAppServerConfig) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *DAppServerConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DAppServerConfig) GetPort() uint64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DAppServerConfig) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

func (m *DAppServerConfig) GetMaxUploadSize() uint64 {
	if m != nil {
		return m.MaxUploadSize
	}
	return 0
}

func (m *DAppServerConfig) GetReadTimeoutMs() uint64 {
	if m != nil {
		return m.ReadTimeoutMs
	}
	return 0
}

func (m *DAppServerConfig) GetWriteTimeoutMs() uint64 {
	if m != nil {
		return m.WriteTimeoutMs
	}
	return 0
}

func (m *DAppServerConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *DAppServerConfig) GetLogFile() string {
	if m != nil {
		return m.LogFile
	}
	return ""
}

func (m *DAppServerConfig) GetLogAge() uint32 {
	if m != nil {
		return m.LogAge
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "dappserverpb.Config")
	proto.RegisterType((*DAppServerConfig)(nil), "dappserverpb.DAppServerConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptorConfig) }

var fileDescriptorConfig = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0xd9, 0x5a, 0xb7, 0xdb, 0x67, 0xab, 0x25, 0x07, 0x8d, 0x08, 0xb2, 0xf4, 0x20, 0x7b,
	0xea, 0x41, 0xef, 0x42, 0xb1, 0x88, 0x07, 0xbd, 0x6c, 0xf5, 0x1c, 0x52, 0xf7, 0x35, 0x06, 0xb2,
	0x4d, 0xc8, 0xa6, 0xb5, 0xf4, 0x97, 0xf9, 0xf3, 0x24, 0x6f, 0x85, 0x2e, 0xde, 0xde, 0xcc, 0x7c,
	0x13, 0x06, 0x02, 0xa3, 0x4f, 0xbb, 0x59, 0x6b, 0x35, 0x73, 0xde, 0x06, 0xcb, 0x46, 0x95, 0x74,
	0xae, 0x41, 0xbf, 0x43, 0xef, 0x56, 0xd3, 0x17, 0x48, 0x9f, 0x28, 0x65, 0x8f, 0x00, 0xc7, 0x84,
	0x27, 0x79, 0x52, 0x9c, 0xdd, 0xdf, 0xce, 0xba, 0xf0, 0x6c, 0x31, 0x77, 0x6e, 0x49, 0xa2, 0xed,
	0x94, 0x9d, 0xc6, 0xf4, 0xa7, 0x07, 0x93, 0xff, 0x00, 0xbb, 0x84, 0x14, 0x37, 0x72, 0x65, 0x90,
	0x1e, 0xcc, 0xca, 0x3f, 0xc5, 0x18, 0xf4, 0xbf, 0x6c, 0x13, 0x78, 0x2f, 0x4f, 0x8a, 0x61, 0x49,
	0x77, 0xf4, 0x9c, 0xf5, 0x81, 0x9f, 0xe4, 0x49, 0xd1, 0x2f, 0xe9, 0x66, 0xd7, 0x90, 0x55, 0x32,
	0x48, 0x51, 0x69, 0xcf, 0xfb, 0xc4, 0x0e, 0xa2, 0x5e, 0x68, 0xcf, 0xee, 0xe0, 0xa2, 0x96, 0x7b,
	0xb1, 0x75, 0xc6, 0xca, 0x4a, 0x34, 0xfa, 0x80, 0xfc, 0x94, 0x9a, 0xe3, 0x5a, 0xee, 0x3f, 0xc8,
	0x5d, 0xea, 0x03, 0x46, 0xce, 0xa3, 0xac, 0x44, 0xd0, 0x35, 0xda, 0x6d, 0x10, 0x75, 0xc3, 0xd3,
	0x96, 0x8b, 0xf6, 0x7b, 0xeb, 0xbe, 0x35, 0xac, 0x80, 0xc9, 0xb7, 0xd7, 0x01, 0xbb, 0xe0, 0x80,
	0xc0, 0x73, 0xf2, 0x8f, 0xe4, 0x0d, 0x0c, 0x8d, 0x55, 0xc2, 0xe0, 0x0e, 0x0d, 0xcf, 0x68, 0x55,
	0x66, 0xac, 0x7a, 0x8d, 0x3a, 0x2e, 0x8e, 0xe1, 0x5a, 0x1b, 0xe4, 0xc3, 0x76, 0xb1, 0xb1, 0xea,
	0x59, 0x1b, 0x64, 0x57, 0x10, 0x4f, 0x21, 0x15, 0x72, 0xc8, 0x93, 0x62, 0x5c, 0xa6, 0xc6, 0xaa,
	0xb9, 0xc2, 0x55, 0x4a, 0x3f, 0xf3, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x53, 0x40, 0x52, 0x30,
	0xa9, 0x01, 0x00, 0x00,
}
