// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config.proto

/*
Package dappserverpb is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	DAppServerConfig
*/
package dappserverpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	DappServer *DAppServerConfig `protobuf:"bytes,1,opt,name=dappServer" json:"dappServer"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{0} }

func (m *Config) GetDappServer() *DAppServerConfig {
	if m != nil {
		return m.DappServer
	}
	return nil
}

type DAppServerConfig struct {
	// Enable
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable"`
	// Host
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host"`
	// Port
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port"`
	// ReadTimeout in millisecond
	ReadTimeoutMs uint32 `protobuf:"varint,4,opt,name=read_timeout_ms,json=readTimeoutMs,proto3" json:"read_timeout_ms"`
	// WriteTimeout in millisecond
	WriteTimeoutMs uint32 `protobuf:"varint,5,opt,name=write_timeout_ms,json=writeTimeoutMs,proto3" json:"write_timeout_ms"`
	// Save log
	SaveLog bool `protobuf:"varint,6,opt,name=save_log,json=saveLog,proto3" json:"save_log"`
	// Log file
	LogFile string `protobuf:"bytes,7,opt,name=log_file,json=logFile,proto3" json:"log_file"`
}

func (m *DAppServerConfig) Reset()                    { *m = DAppServerConfig{} }
func (m *DAppServerConfig) String() string            { return proto.CompactTextString(m) }
func (*DAppServerConfig) ProtoMessage()               {}
func (*DAppServerConfig) Descriptor() ([]byte, []int) { return fileDescriptorConfig, []int{1} }

func (m *DAppServerConfig) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *DAppServerConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DAppServerConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *DAppServerConfig) GetReadTimeoutMs() uint32 {
	if m != nil {
		return m.ReadTimeoutMs
	}
	return 0
}

func (m *DAppServerConfig) GetWriteTimeoutMs() uint32 {
	if m != nil {
		return m.WriteTimeoutMs
	}
	return 0
}

func (m *DAppServerConfig) GetSaveLog() bool {
	if m != nil {
		return m.SaveLog
	}
	return false
}

func (m *DAppServerConfig) GetLogFile() string {
	if m != nil {
		return m.LogFile
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "dappserverpb.Config")
	proto.RegisterType((*DAppServerConfig)(nil), "dappserverpb.DAppServerConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptorConfig) }

var fileDescriptorConfig = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x89, 0xd6, 0xdd, 0x3a, 0xb6, 0x5a, 0x72, 0x90, 0x78, 0x91, 0xa5, 0x07, 0xd9, 0xd3,
	0x1e, 0xf4, 0x2e, 0x88, 0x22, 0x1e, 0xf4, 0xb2, 0x7a, 0x5f, 0xb2, 0x76, 0x1a, 0x03, 0x69, 0x27,
	0x24, 0xb1, 0xbe, 0xab, 0x4f, 0x23, 0x99, 0x55, 0x5c, 0x7a, 0x9b, 0xf9, 0xbf, 0x6f, 0xc2, 0x4f,
	0x60, 0xf6, 0x4e, 0xdb, 0xb5, 0x35, 0x8d, 0x0f, 0x94, 0x48, 0xce, 0x56, 0xda, 0xfb, 0x88, 0x61,
	0x87, 0xc1, 0xf7, 0xcb, 0x27, 0x28, 0xee, 0x99, 0xca, 0x5b, 0x80, 0x4c, 0x5e, 0x99, 0x28, 0x51,
	0x89, 0xfa, 0xe4, 0xfa, 0xb2, 0x19, 0xcb, 0xcd, 0xc3, 0xdd, 0x1f, 0x1f, 0x6e, 0xda, 0xd1, 0xc5,
	0xf2, 0x5b, 0xc0, 0x62, 0x5f, 0x90, 0xe7, 0x50, 0xe0, 0x56, 0xf7, 0x0e, 0xf9, 0xc1, 0x69, 0xfb,
	0xbb, 0x49, 0x09, 0x93, 0x0f, 0x8a, 0x49, 0x1d, 0x54, 0xa2, 0x3e, 0x6e, 0x79, 0xce, 0x99, 0xa7,
	0x90, 0xd4, 0x61, 0x25, 0xea, 0x79, 0xcb, 0xb3, 0xbc, 0x82, 0xb3, 0x80, 0x7a, 0xd5, 0x25, 0xbb,
	0x41, 0xfa, 0x4c, 0xdd, 0x26, 0xaa, 0x09, 0xe3, 0x79, 0x8e, 0xdf, 0x86, 0xf4, 0x25, 0xca, 0x1a,
	0x16, 0x5f, 0xc1, 0x26, 0x1c, 0x8b, 0x47, 0x2c, 0x9e, 0x72, 0xfe, 0x6f, 0x5e, 0xc0, 0x34, 0xea,
	0x1d, 0x76, 0x8e, 0x8c, 0x2a, 0xb8, 0x53, 0x99, 0xf7, 0x67, 0x32, 0x19, 0x39, 0x32, 0xdd, 0xda,
	0x3a, 0x54, 0x25, 0x17, 0x2b, 0x1d, 0x99, 0x47, 0xeb, 0xb0, 0x2f, 0xf8, 0xef, 0x6e, 0x7e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xbf, 0x79, 0x21, 0x4b, 0x01, 0x00, 0x00,
}
